pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/AlanBerrios/tingeso-2-2024']])
                dir("frontendprestabanco"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("frontendprestabanco"){
                    script{
                        bat "docker context use default"
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t alanberrios/prestabancofrontend-image:latest ."
                            bat "docker push alanberrios/prestabancofrontend-image:latest"
                        }
                    }                    
                }
            }
        }
    }
}