server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/clients/**

        - id: ms-creditsimulation
          uri: lb://ms-creditsimulation
          predicates:
            - Path=/credit-simulations/**

        - id: ms-creditrequest
          uri: lb://ms-creditrequest
          predicates:
            - Path=/credit-requests/**,/mortgage-loans/**

        - id: ms-creditevaluation
          uri: lb://ms-creditevaluation
          predicates:
            - Path=/account-history/**,/credit-evaluations/**,/debts/**,/savings-accounts/**

        - id: ms-requesttracking
          uri: lb://ms-requesttracking
          predicates:
            - Path=/request-tracking/**
            
        - id: ms-totalcost
          uri: lb://ms-totalcost
          predicates:
            - Path=/loan-cost/**

        - id: ms-userregister
          uri: lb://ms-userregister
          predicates:
            - Path=/client-documents/**,/documentation/**,/jobs/**
      