apiVersion: v1
kind: PersistentVolume
metadata:
  name: creditrequest-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/creditrequest-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creditrequest-db-pvc
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditrequest-db-deployment
  labels:
    app: creditrequest-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: creditrequest-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: creditrequest-db-deployment
        tier: database
    spec:
      containers:
        - name: creditrequest-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_CLIENT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_CLIENT
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: creditrequest-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: creditrequest-db-storage
          persistentVolumeClaim:
            claimName: creditrequest-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: creditrequest-db-service
  labels:
    app: creditrequest-db-service
    tier: database
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: creditrequest-db-deployment
    tier: database
  type: LoadBalancer