apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-totalcost-deployment
  labels:
    app: ms-totalcost-deployment
spec:
  selector:
    matchLabels:
      app: ms-totalcost-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-totalcost-deployment
    spec:
      containers:
        - name: ms-totalcost
          image: alanberrios/ms-totalcost
          ports:
            - containerPort: 8006
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_TOTALCOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_TOTALCOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_NAME_TOTALCOST
            - name: DB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_CLIENT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD


