apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-userregister-deployment
  labels:
    app: ms-userregister-deployment
spec:
  selector:
    matchLabels:
      app: ms-userregister-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-userregister-deployment
    spec:
      containers:
        - name: ms-userregister
          image: alanberrios/ms-userregister
          ports:
            - containerPort: 8007
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_USERREGISTER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_USERREGISTER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_NAME_USERREGISTER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD


